DROP TABLE fornada;
DROP TABLE pao;


-- ======================================
-- Criar tabela pao
-- ======================================
CREATE TABLE pao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(120) NOT NULL,
    tempo_preparo_minutos INT NOT NULL,
    cor_hex VARCHAR(16) NOT NULL
);

-- ======================================
-- Criar tabela fornada
-- ======================================
CREATE TABLE fornada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pao_id BIGINT NOT NULL,
    inicio TIMESTAMP NOT NULL,
    CONSTRAINT fk_fornada_pao FOREIGN KEY (pao_id) REFERENCES pao(id)
);
